import { beforeAll, afterAll, describe, expect, it } from "vitest";
import { createDatabase, authSessions, channels, contacts, conversations, integrationAccounts, messages, opportunities, opportunityActivities, organizationMembers, organizations, pipelineStages, pipelines, users, webhookEvents } from "@echat/db";
import { MockMessagingProvider } from "./providers.js";
import { hashPassword, hashSessionToken } from "./auth.js";
import { Repositories } from "./repositories.js";
import { DomainServices } from "./services.js";
import type { SessionUser } from "@echat/shared";
import { eq, inArray } from "drizzle-orm";

const databaseUrl = process.env.DATABASE_URL_TEST;
const dbRuntime = databaseUrl ? createDatabase(databaseUrl) : null;
if (!databaseUrl) console.warn("POSTGRES_INTEGRATION_TESTS=BLOCKED_NO_TEST_DATABASE");
const ids = { orgA: "integration-org-a", orgB: "integration-org-b", userA: "integration-user-a", userB: "integration-user-b", contactA: "integration-contact-a", contactB: "integration-contact-b", channelA: "integration-channel-a", channelB: "integration-channel-b", conversationA: "integration-conversation-a", conversationB: "integration-conversation-b", pipelineA: "integration-pipeline-a", stageA: "integration-stage-a", stageB: "integration-stage-b", opportunityA: "integration-opportunity-a", integrationA: "integration-account-a" };
const actor = (organizationId: string, id: string): SessionUser => ({ id, organizationId, name: "Integration Agent", email: `${id}@local`, role: "AGENT", avatar: "IA", sessionId: "integration-session" });

describe.skipIf(!databaseUrl)("PostgreSQL production foundation", () => {
  if (!dbRuntime) return;
  const { db, client } = dbRuntime; const repositories = new Repositories(db); const services = new DomainServices(repositories, new MockMessagingProvider());
  beforeAll(async () => {
    await db.insert(organizations).values([{ id: ids.orgA, name: "Integration A", plan: "test" }, { id: ids.orgB, name: "Integration B", plan: "test" }]).onConflictDoNothing();
    await db.insert(users).values([{ id: ids.userA, email: "integration-a@local", name: "A", passwordHash: hashPassword("local-only"), avatar: "A" }, { id: ids.userB, email: "integration-b@local", name: "B", passwordHash: hashPassword("local-only"), avatar: "B" }]).onConflictDoNothing();
    await db.insert(organizationMembers).values([{ id: "integration-member-a", organizationId: ids.orgA, userId: ids.userA, role: "AGENT", status: "ACTIVE" }, { id: "integration-member-b", organizationId: ids.orgB, userId: ids.userB, role: "AGENT", status: "ACTIVE" }]).onConflictDoNothing();
    await db.insert(channels).values([{ id: ids.channelA, organizationId: ids.orgA, name: "Test A", type: "WEBCHAT", status: "CONNECTED", conversations: 0 }, { id: ids.channelB, organizationId: ids.orgB, name: "Test B", type: "WEBCHAT", status: "CONNECTED", conversations: 0 }]).onConflictDoNothing();
    await db.insert(contacts).values([{ id: ids.contactA, organizationId: ids.orgA, name: "Contact A", company: "A", phone: "", email: "a@local", ownerId: ids.userA, notes: "", lastConversationAt: new Date() }, { id: ids.contactB, organizationId: ids.orgB, name: "Contact B", company: "B", phone: "", email: "b@local", ownerId: ids.userB, notes: "", lastConversationAt: new Date() }]).onConflictDoNothing();
    await db.insert(conversations).values([{ id: ids.conversationA, organizationId: ids.orgA, externalId: "external-a", contactId: ids.contactA, channelId: ids.channelA, status: "OPEN", assignedToId: ids.userA, unread: 0, lastMessage: "initial", lastMessageAt: new Date() }, { id: ids.conversationB, organizationId: ids.orgB, externalId: "external-b", contactId: ids.contactB, channelId: ids.channelB, status: "OPEN", assignedToId: ids.userB, unread: 0, lastMessage: "initial", lastMessageAt: new Date() }]).onConflictDoNothing();
    await db.insert(pipelines).values({ id: ids.pipelineA, organizationId: ids.orgA, name: "Test pipeline" }).onConflictDoNothing(); await db.insert(pipelineStages).values([{ id: ids.stageA, organizationId: ids.orgA, pipelineId: ids.pipelineA, name: "Novo", key: "NEW_LEAD", position: 1, color: "teal" }, { id: ids.stageB, organizationId: ids.orgA, pipelineId: ids.pipelineA, name: "Negociação", key: "NEGOTIATION", position: 2, color: "amber" }]).onConflictDoNothing();
    await db.insert(opportunities).values({ id: ids.opportunityA, organizationId: ids.orgA, title: "Test opp", contactId: ids.contactA, company: "A", value: "10.00", pipelineId: ids.pipelineA, stageId: ids.stageA, ownerId: ids.userA, source: "test", lastActivity: "now", note: "test" }).onConflictDoNothing(); await db.insert(integrationAccounts).values({ id: ids.integrationA, organizationId: ids.orgA, provider: "mock", externalAccountId: "integration-account", status: "ACTIVE", metadata: {} }).onConflictDoNothing();
  });
  afterAll(async () => { await db.delete(webhookEvents).where(eq(webhookEvents.integrationAccountId, ids.integrationA)); await db.delete(authSessions).where(inArray(authSessions.userId, [ids.userA, ids.userB])); await db.delete(opportunityActivities).where(eq(opportunityActivities.organizationId, ids.orgA)); await db.delete(messages).where(inArray(messages.organizationId, [ids.orgA, ids.orgB])); await db.delete(opportunities).where(eq(opportunities.organizationId, ids.orgA)); await db.delete(conversations).where(inArray(conversations.organizationId, [ids.orgA, ids.orgB])); await db.delete(pipelineStages).where(eq(pipelineStages.organizationId, ids.orgA)); await db.delete(pipelines).where(eq(pipelines.organizationId, ids.orgA)); await db.delete(contacts).where(inArray(contacts.organizationId, [ids.orgA, ids.orgB])); await db.delete(channels).where(inArray(channels.organizationId, [ids.orgA, ids.orgB])); await db.delete(integrationAccounts).where(eq(integrationAccounts.id, ids.integrationA)); await db.delete(organizationMembers).where(inArray(organizationMembers.organizationId, [ids.orgA, ids.orgB])); await db.delete(users).where(inArray(users.id, [ids.userA, ids.userB])); await db.delete(organizations).where(inArray(organizations.id, [ids.orgA, ids.orgB])); await client.end(); });
  it("persists sessions and rejects cross-tenant records", async () => { const token = "opaque-integration-token"; const tokenHash = hashSessionToken(token); const sessionId = "integration-session-row"; await repositories.createSession({ id: sessionId, userId: ids.userA, organizationId: ids.orgA, tokenHash, expiresAt: new Date(Date.now() + 60_000) }); expect((await repositories.findSession(tokenHash))?.user.organizationId).toBe(ids.orgA); expect((await repositories.listContacts(ids.orgA)).map((item) => item.id)).toContain(ids.contactA); expect((await repositories.listContacts(ids.orgA)).map((item) => item.id)).not.toContain(ids.contactB); await repositories.revokeSession(sessionId); expect(await repositories.findSession(tokenHash)).toBeNull(); });
  it("persists message, CRM activity, and inbound webhook idempotency", async () => { const message = await services.sendMessage(actor(ids.orgA, ids.userA), ids.conversationA, { body: "persisted" }); expect((await repositories.listConversations(ids.orgA)).find((item) => item.id === ids.conversationA)?.messages.some((item) => item.body === "persisted")).toBe(true); const moved = await services.moveOpportunity(actor(ids.orgA, ids.userA), ids.opportunityA, { stage: "NEGOTIATION" }); expect(moved.stage).toBe("NEGOTIATION"); expect((await db.select().from(opportunityActivities).where(eq(opportunityActivities.opportunityId, ids.opportunityA))).length).toBeGreaterThan(0); const payload = { event: "message_created", id: "integration-event-1", account: { id: "integration-account" }, conversation: { id: "external-a" }, message: { id: "integration-message-1", content: "inbound" } }; const first = await services.processWebhook({ integrationAccountId: ids.integrationA, organizationId: ids.orgA, provider: "mock", eventId: "integration-event-1", rawBody: JSON.stringify(payload), payload }); const second = await services.processWebhook({ integrationAccountId: ids.integrationA, organizationId: ids.orgA, provider: "mock", eventId: "integration-event-1", rawBody: JSON.stringify(payload), payload }); expect(first).toEqual({ processed: true, duplicate: false }); expect(second).toEqual({ processed: false, duplicate: true }); expect((await db.select().from(messages).where(eq(messages.externalId, "integration-message-1"))).length).toBe(1); expect(message.body).toBe("persisted"); });
});
