import { createDatabase, channels, contacts, contactTags, conversations, integrationAccounts, messages, opportunities, opportunityActivities, organizationMembers, organizations, pipelineStages, pipelines, tags, users } from "@echat/db";
import { createSeedState } from "./seed-data.js";
import { hashPassword } from "./auth.js";

if (process.env.NODE_ENV === "production") throw new Error("Seed demo bloqueado quando NODE_ENV=production");
const { db, client } = createDatabase();
const state = createSeedState();
const passwordHash = hashPassword("local-only");
const colorByTag: Record<string, string> = { "Lead qualificado": "teal", Instagram: "pink", "Plano Pro": "violet", Cliente: "green", Suporte: "blue", Demonstração: "amber", API: "blue", WebChat: "teal", Financeiro: "slate" };

try {
  await db.transaction(async (tx) => {
    await tx.insert(organizations).values({ id: state.organization.id, name: state.organization.name, plan: state.organization.plan }).onConflictDoUpdate({ target: organizations.id, set: { name: state.organization.name, plan: state.organization.plan } });
    for (const user of state.users) {
      await tx.insert(users).values({ id: user.id, email: user.email, name: user.name, passwordHash, avatar: user.avatar }).onConflictDoUpdate({ target: users.id, set: { name: user.name, avatar: user.avatar, passwordHash } });
      await tx.insert(organizationMembers).values({ id: `membership-${user.id}`, organizationId: state.organization.id, userId: user.id, role: user.role, status: "ACTIVE" }).onConflictDoUpdate({ target: [organizationMembers.organizationId, organizationMembers.userId], set: { role: user.role, status: "ACTIVE", updatedAt: new Date() } });
    }
    for (const channel of state.channels) await tx.insert(channels).values({ id: channel.id, organizationId: channel.organizationId, externalId: null, name: channel.name, type: channel.type, status: channel.status, conversations: channel.conversations }).onConflictDoUpdate({ target: channels.id, set: { name: channel.name, status: channel.status, conversations: channel.conversations, updatedAt: new Date() } });
    for (const contact of state.contacts) await tx.insert(contacts).values({ id: contact.id, organizationId: contact.organizationId, externalId: null, name: contact.name, company: contact.company, phone: contact.phone, email: contact.email, ownerId: contact.ownerId, notes: contact.notes, lastConversationAt: new Date(contact.lastConversationAt) }).onConflictDoUpdate({ target: contacts.id, set: { name: contact.name, company: contact.company, phone: contact.phone, email: contact.email, ownerId: contact.ownerId, notes: contact.notes, lastConversationAt: new Date(contact.lastConversationAt), updatedAt: new Date() } });
    const pipelineId = `${state.organization.id}-pipeline-default`; await tx.insert(pipelines).values({ id: pipelineId, organizationId: state.organization.id, name: "Pipeline principal" }).onConflictDoUpdate({ target: pipelines.id, set: { name: "Pipeline principal", updatedAt: new Date() } });
    const stageByKey = new Map<string, string>(); for (const stage of state.stages) { const stageId = `${state.organization.id}-stage-${stage.key}`; stageByKey.set(stage.key, stageId); await tx.insert(pipelineStages).values({ id: stageId, organizationId: stage.organizationId, pipelineId, name: stage.name, key: stage.key, position: stage.order, color: stage.color }).onConflictDoUpdate({ target: pipelineStages.id, set: { name: stage.name, key: stage.key, position: stage.order, color: stage.color, updatedAt: new Date() } }); }
    const uniqueTags = [...new Set(state.contacts.flatMap((contact) => contact.tags))]; for (const name of uniqueTags) { const tagId = `tag-${name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`; await tx.insert(tags).values({ id: tagId, organizationId: state.organization.id, name, color: colorByTag[name] ?? "slate" }).onConflictDoUpdate({ target: [tags.organizationId, tags.name], set: { color: colorByTag[name] ?? "slate", updatedAt: new Date() } }); for (const contact of state.contacts.filter((item) => item.tags.includes(name))) await tx.insert(contactTags).values({ id: `contact-tag-${contact.id}-${tagId}`, organizationId: state.organization.id, contactId: contact.id, tagId }).onConflictDoNothing({ target: [contactTags.contactId, contactTags.tagId] }); }
    for (const conversation of state.conversations) { await tx.insert(conversations).values({ id: conversation.id, organizationId: conversation.organizationId, externalId: null, contactId: conversation.contactId, channelId: conversation.channelId, status: conversation.status, assignedToId: conversation.assignedToId ?? null, unread: conversation.unread, lastMessage: conversation.lastMessage, lastMessageAt: new Date(conversation.lastMessageAt) }).onConflictDoUpdate({ target: conversations.id, set: { status: conversation.status, assignedToId: conversation.assignedToId ?? null, unread: conversation.unread, lastMessage: conversation.lastMessage, lastMessageAt: new Date(conversation.lastMessageAt), updatedAt: new Date() } }); for (const message of conversation.messages) await tx.insert(messages).values({ id: message.id, organizationId: state.organization.id, conversationId: conversation.id, externalId: null, sender: message.sender, authorName: message.authorName, body: message.body, internal: message.internal ?? false, createdAt: new Date(message.createdAt) }).onConflictDoNothing({ target: messages.id }); }
    for (const opportunity of state.opportunities) { const stageId = stageByKey.get(opportunity.stage); if (!stageId) continue; await tx.insert(opportunities).values({ id: opportunity.id, organizationId: opportunity.organizationId, title: opportunity.title, contactId: opportunity.contactId, company: opportunity.company, value: opportunity.value.toFixed(2), pipelineId, stageId, ownerId: opportunity.ownerId, source: opportunity.source, lastActivity: opportunity.lastActivity, note: opportunity.note }).onConflictDoUpdate({ target: opportunities.id, set: { title: opportunity.title, company: opportunity.company, value: opportunity.value.toFixed(2), stageId, ownerId: opportunity.ownerId, lastActivity: opportunity.lastActivity, note: opportunity.note, updatedAt: new Date() } }); await tx.insert(opportunityActivities).values({ id: `activity-seed-${opportunity.id}`, organizationId: state.organization.id, opportunityId: opportunity.id, actorId: opportunity.ownerId, type: "SEEDED", detail: "Oportunidade inicial do workspace" }).onConflictDoNothing({ target: opportunityActivities.id }); }
    const provider = process.env.MESSAGING_PROVIDER === "chatwoot" ? "chatwoot" : "mock"; const externalAccountId = provider === "chatwoot" ? process.env.CHATWOOT_ACCOUNT_ID ?? "" : "mock"; if (externalAccountId) await tx.insert(integrationAccounts).values({ id: `integration-${provider}-${externalAccountId}`, organizationId: state.organization.id, provider, externalAccountId, status: "ACTIVE", baseUrl: provider === "chatwoot" ? process.env.CHATWOOT_BASE_URL ?? null : null, credentialRef: provider === "chatwoot" ? "CHATWOOT_API_TOKEN" : null, metadata: {} }).onConflictDoUpdate({ target: integrationAccounts.id, set: { organizationId: state.organization.id, status: "ACTIVE", baseUrl: provider === "chatwoot" ? process.env.CHATWOOT_BASE_URL ?? null : null, updatedAt: new Date() } });
  });
  console.log("Seed PostgreSQL idempotente concluído para Acme Atendimento");
} finally { await client.end(); }
