import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { randomUUID } from "node:crypto";
import { acceptInviteSchema, assignConversationSchema, createOpportunitySchema, integrationSchema, inviteSchema, loginSchema, memberUpdateSchema, organizationSettingsSchema, signupSchema } from "@echat/shared";
import { createDatabase } from "@echat/db";
import { createSessionToken, hashSessionToken, verifyPassword } from "./auth.js";
import { createMessagingProvider } from "./providers.js";
import { DomainError, DomainServices } from "./services.js";
import { Repositories } from "./repositories.js";

const port = Number(process.env.PORT ?? 3001); const appUrl = process.env.APP_URL ?? "http://localhost:5173"; const cookieName = process.env.SESSION_COOKIE_NAME ?? "echat_session"; const sessionTtlHours = Number(process.env.SESSION_TTL_HOURS ?? 168); const sessionSecret = process.env.SESSION_SECRET ?? "development-only-change-me"; const maxBodyBytes = 1_048_576; const { db, client } = createDatabase(); const repositories = new Repositories(db); const provider = createMessagingProvider(); const services = new DomainServices(repositories, provider); const loginAttempts = new Map<string, { count: number; resetAt: number }>(); const signupAttempts = new Map<string, { count: number; resetAt: number }>(); const inviteAttempts = new Map<string, { count: number; resetAt: number }>(); const connectionAttempts = new Map<string, { count: number; resetAt: number }>();
const json = (res: ServerResponse, status: number, payload: unknown, headers: Record<string, string> = {}) => { res.writeHead(status, { "Content-Type": "application/json; charset=utf-8", "Access-Control-Allow-Origin": appUrl, "Access-Control-Allow-Credentials": "true", "Vary": "Origin", ...headers }); res.end(JSON.stringify(payload)); };
const parseCookies = (header: string | undefined): Record<string, string> => Object.fromEntries((header ?? "").split(";").map((part) => { const index = part.indexOf("="); return index < 0 ? ["", ""] : [part.slice(0, index).trim(), decodeURIComponent(part.slice(index + 1).trim())]; }).filter(([key, value]) => Boolean(key && value)));
const firstHeader = (value: string | string[] | undefined): string | undefined => Array.isArray(value) ? value[0] : value;
const sessionHash = (token: string) => hashSessionToken(`${token}.${sessionSecret}`);
const secureCookie = process.env.NODE_ENV === "production" || appUrl.startsWith("https://");
const sessionCookie = (token: string, maxAge: number) => `${cookieName}=${encodeURIComponent(token)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${maxAge}${secureCookie ? "; Secure" : ""}`;
const newSession = () => { const token = createSessionToken(); const ttlSeconds = Math.max(300, sessionTtlHours * 3600); return { token, ttlSeconds, id: randomUUID(), tokenHash: sessionHash(token), expiresAt: new Date(Date.now() + ttlSeconds * 1000) }; };
const readRawBody = (req: IncomingMessage, limit = maxBodyBytes): Promise<string> => new Promise((resolveBody, reject) => { let raw = ""; let size = 0; let settled = false; req.on("data", (chunk: Buffer) => { if (settled) return; size += chunk.byteLength; if (size > limit) { settled = true; reject(new DomainError(413, "Payload muito grande")); req.resume(); return; } raw += chunk.toString("utf8"); }); req.on("end", () => { if (!settled) { settled = true; resolveBody(raw); } }); req.on("error", (error) => { if (!settled) { settled = true; reject(error); } }); });
const readBody = async (req: IncomingMessage): Promise<unknown> => { const raw = await readRawBody(req); try { return raw ? JSON.parse(raw) : {}; } catch { throw new DomainError(400, "JSON inválido"); } };
const rejectForeignOrigin = (req: IncomingMessage) => { const origin = firstHeader(req.headers.origin); if (origin && origin !== appUrl) throw new DomainError(403, "Origem não permitida"); };
const requireSession = async (req: IncomingMessage) => { const token = parseCookies(req.headers.cookie)[cookieName]; if (!token) throw new DomainError(401, "Sessão necessária"); const session = await repositories.findSession(sessionHash(token)); if (!session) throw new DomainError(401, "Sessão necessária"); return session.user; };
const takeLoginAttempt = (key: string): boolean => { const now = Date.now(); const current = loginAttempts.get(key); if (!current || current.resetAt <= now) { loginAttempts.set(key, { count: 1, resetAt: now + 15 * 60_000 }); return true; } if (current.count >= 10) return false; current.count += 1; return true; };
const takeLimited = (store: Map<string, { count: number; resetAt: number }>, key: string, max: number): boolean => { const now = Date.now(); const current = store.get(key); if (!current || current.resetAt <= now) { store.set(key, { count: 1, resetAt: now + 15 * 60_000 }); return true; } if (current.count >= max) return false; current.count += 1; return true; };
const externalAccountFromPayload = (payload: unknown): string | undefined => { if (!payload || typeof payload !== "object") return undefined; const value = payload as Record<string, unknown>; const account = value.account; if (account && typeof account === "object") { const accountRecord = account as Record<string, unknown>; if (typeof accountRecord.id === "string" || typeof accountRecord.id === "number") return String(accountRecord.id); } if (typeof value.account_id === "string" || typeof value.account_id === "number") return String(value.account_id); return undefined; };
const publicUser = (session: Awaited<ReturnType<typeof repositories.findSession>>) => session?.user;

const route = async (req: IncomingMessage, res: ServerResponse) => {
  const url = new URL(req.url ?? "/", `http://${req.headers.host ?? "localhost"}`);
  if (req.method === "OPTIONS") { const origin = firstHeader(req.headers.origin); if (origin && origin !== appUrl) { res.writeHead(403); res.end(); return; } res.writeHead(204, { "Access-Control-Allow-Origin": appUrl, "Access-Control-Allow-Credentials": "true", "Access-Control-Allow-Headers": "Content-Type, X-Chatwoot-Timestamp, X-Chatwoot-Signature, X-Chatwoot-Delivery", "Access-Control-Allow-Methods": "GET,POST,PATCH,DELETE,OPTIONS" }); res.end(); return; }
  if (url.pathname === "/api/health") { json(res, 200, { ok: true, provider: provider.name }); return; }
  try {
    if (req.method === "POST" && url.pathname === "/api/v1/auth/signup") { rejectForeignOrigin(req); if (!takeLimited(signupAttempts, req.socket.remoteAddress ?? "unknown", 5)) throw new DomainError(429, "Muitas tentativas de cadastro. Tente novamente mais tarde."); const input = signupSchema.parse(await readBody(req)); const session = newSession(); const result = await services.signup({ ...input, session: { id: session.id, tokenHash: session.tokenHash, expiresAt: session.expiresAt } }); const authenticated = await repositories.findSession(session.tokenHash); json(res, 201, { user: publicUser(authenticated), organizationId: result.organizationId }, { "Set-Cookie": sessionCookie(session.token, session.ttlSeconds) }); return; }
    const inviteMatch = url.pathname.match(/^\/api\/v1\/invites\/([^/]+)$/);
    if (req.method === "GET" && inviteMatch) { json(res, 200, await services.inviteInfo(decodeURIComponent(inviteMatch[1]))); return; }
    if (req.method === "POST" && inviteMatch) { rejectForeignOrigin(req); if (!takeLimited(inviteAttempts, req.socket.remoteAddress ?? "unknown", 5)) throw new DomainError(429, "Muitas tentativas de convite. Tente novamente mais tarde."); const input = acceptInviteSchema.parse(await readBody(req)); const session = newSession(); const result = await services.acceptInvite({ ...input, token: decodeURIComponent(inviteMatch[1]), session: { id: session.id, tokenHash: session.tokenHash, expiresAt: session.expiresAt } }); const authenticated = await repositories.findSession(session.tokenHash); json(res, 201, { user: publicUser(authenticated), organizationId: result.organizationId }, { "Set-Cookie": sessionCookie(session.token, session.ttlSeconds) }); return; }
    if (req.method === "POST" && url.pathname === "/api/v1/auth/login") { rejectForeignOrigin(req); const attemptKey = req.socket.remoteAddress ?? "unknown"; if (!takeLoginAttempt(attemptKey)) throw new DomainError(429, "Muitas tentativas. Tente novamente mais tarde."); const input = loginSchema.parse(await readBody(req)); const found = await repositories.authenticate(input.email.toLowerCase()); if (!found || !verifyPassword(input.password, found.passwordHash)) { json(res, 401, { error: "Email ou senha inválidos" }); return; } const session = newSession(); await repositories.createSession({ id: session.id, userId: found.userId, organizationId: found.user.organizationId, tokenHash: session.tokenHash, expiresAt: session.expiresAt }); const authenticated = await repositories.findSession(session.tokenHash); json(res, 200, { user: publicUser(authenticated) }, { "Set-Cookie": sessionCookie(session.token, session.ttlSeconds) }); return; }
    if (req.method === "POST" && url.pathname === "/api/v1/auth/logout") { rejectForeignOrigin(req); const token = parseCookies(req.headers.cookie)[cookieName]; if (token) { const session = await repositories.findSession(sessionHash(token)); if (session) await repositories.revokeSession(session.sessionId); } json(res, 200, { ok: true }, { "Set-Cookie": sessionCookie("", 0) }); return; }
    if (req.method === "POST" && url.pathname === "/api/v1/webhooks/chatwoot") { const rawBody = await readRawBody(req); let rawPayload: unknown; try { rawPayload = rawBody ? JSON.parse(rawBody) : {}; } catch { throw new DomainError(400, "JSON inválido"); } const externalAccountId = externalAccountFromPayload(rawPayload); if (!externalAccountId) throw new DomainError(400, "Conta externa ausente"); const integration = await repositories.findIntegrationByExternalAccountId(externalAccountId); if (!integration) throw new DomainError(404, "Integração não encontrada"); const integrationProvider = await services.providerForWebhook(integration.organizationId, integration.id); if (integrationProvider.name === "chatwoot" && !integrationProvider.verifyWebhook?.({ "x-chatwoot-timestamp": firstHeader(req.headers["x-chatwoot-timestamp"]), "x-chatwoot-signature": firstHeader(req.headers["x-chatwoot-signature"]) }, rawBody)) throw new DomainError(401, "Assinatura Chatwoot inválida"); const eventId = firstHeader(req.headers["x-chatwoot-delivery"]) ?? firstHeader(req.headers["x-chatwoot-event-id"]) ?? (rawPayload && typeof rawPayload === "object" && (typeof (rawPayload as Record<string, unknown>).id === "string" || typeof (rawPayload as Record<string, unknown>).id === "number") ? String((rawPayload as Record<string, unknown>).id) : undefined); if (!eventId) throw new DomainError(400, "X-Chatwoot-Delivery obrigatório"); json(res, 200, await services.processWebhook({ integrationAccountId: integration.id, organizationId: integration.organizationId, provider: integration.provider, eventId, rawBody, payload: rawPayload, providerInstance: integrationProvider })); return; }
    const user = await requireSession(req); if (["POST", "PATCH", "DELETE"].includes(req.method ?? "")) rejectForeignOrigin(req);
    if (req.method === "GET" && url.pathname === "/api/v1/auth/me") { json(res, 200, { user }); return; }
    if (req.method === "GET" && url.pathname === "/api/v1/bootstrap") { json(res, 200, await services.bootstrap(user)); return; }
    if (req.method === "GET" && url.pathname === "/api/v1/organization") { json(res, 200, { organization: await repositories.getOrganization(user.organizationId) }); return; }
    if (req.method === "PATCH" && url.pathname === "/api/v1/organization") { json(res, 200, { organization: await services.updateOrganization(user, organizationSettingsSchema.parse(await readBody(req))) }); return; }
    if (req.method === "GET" && url.pathname === "/api/v1/members") { json(res, 200, { members: await services.listMembers(user) }); return; }
    const memberMatch = url.pathname.match(/^\/api\/v1\/members\/([^/]+)$/); if (req.method === "PATCH" && memberMatch) { json(res, 200, { member: await services.updateMember(user, memberMatch[1], memberUpdateSchema.parse(await readBody(req))) }); return; }
    if (req.method === "GET" && url.pathname === "/api/v1/members/invites") { json(res, 200, { invites: await services.listInvites(user) }); return; }
    if (req.method === "POST" && url.pathname === "/api/v1/members/invites") { const input = inviteSchema.parse(await readBody(req)); json(res, 201, await services.createInvite(user, { ...input, appUrl })); return; }
    const inviteAdminMatch = url.pathname.match(/^\/api\/v1\/members\/invites\/([^/]+)$/); if (req.method === "DELETE" && inviteAdminMatch) { json(res, 200, await services.revokeInvite(user, inviteAdminMatch[1])); return; }
    if (req.method === "GET" && url.pathname === "/api/v1/integrations") { json(res, 200, { integrations: await services.listIntegrations(user) }); return; }
    if (req.method === "POST" && url.pathname === "/api/v1/integrations") { json(res, 201, { integration: await services.saveIntegration(user, integrationSchema.parse(await readBody(req))) }); return; }
    const integrationMatch = url.pathname.match(/^\/api\/v1\/integrations\/([^/]+)(?:\/(test|sync))?$/); if (integrationMatch && req.method === "POST" && integrationMatch[2] === "test") { if (!takeLimited(connectionAttempts, user.id, 10)) throw new DomainError(429, "Muitos testes de conexão. Tente novamente mais tarde."); json(res, 200, await services.testIntegration(user, integrationMatch[1])); return; } if (integrationMatch && req.method === "POST" && integrationMatch[2] === "sync") { json(res, 200, await services.syncIntegration(user, integrationMatch[1])); return; } if (integrationMatch && req.method === "DELETE" && !integrationMatch[2]) { json(res, 200, await services.deleteIntegration(user, integrationMatch[1])); return; }
    if (req.method === "GET" && url.pathname === "/api/v1/contacts") { const query = url.searchParams.get("query") ?? ""; if (query || url.searchParams.has("page")) { const result = await services.searchContacts(user, query, Number(url.searchParams.get("page") ?? 1), Number(url.searchParams.get("pageSize") ?? 25)); json(res, 200, { contacts: result.items, pagination: result }); } else json(res, 200, { contacts: await services.listContacts(user) }); return; }
    if (req.method === "GET" && url.pathname === "/api/v1/conversations") { const hasFilters = ["query", "status", "assignedToId", "channelId", "page"].some((key) => url.searchParams.has(key)); if (hasFilters) { const result = await services.searchConversations(user, { query: url.searchParams.get("query") ?? undefined, status: url.searchParams.get("status") ?? undefined, assignedToId: url.searchParams.get("assignedToId") ?? undefined, channelId: url.searchParams.get("channelId") ?? undefined, page: Number(url.searchParams.get("page") ?? 1), pageSize: Number(url.searchParams.get("pageSize") ?? 25) }); json(res, 200, { conversations: result.items, pagination: result }); } else json(res, 200, { conversations: await services.listConversations(user) }); return; }
    const conversationMatch = url.pathname.match(/^\/api\/v1\/conversations\/([^/]+)$/); if (req.method === "GET" && conversationMatch) { json(res, 200, await services.getConversation(user, conversationMatch[1])); return; }
    const messageMatch = url.pathname.match(/^\/api\/v1\/conversations\/([^/]+)\/messages$/); if (req.method === "POST" && messageMatch) { json(res, 201, { message: await services.sendMessage(user, messageMatch[1], await readBody(req)) }); return; }
    const assignMatch = url.pathname.match(/^\/api\/v1\/conversations\/([^/]+)\/assign$/); if (req.method === "PATCH" && assignMatch) { json(res, 200, { conversation: await services.assignConversation(user, assignMatch[1], await readBody(req)) }); return; }
    const statusMatch = url.pathname.match(/^\/api\/v1\/conversations\/([^/]+)\/(resolve|reopen)$/); if (req.method === "POST" && statusMatch) { json(res, 200, { conversation: await services.updateConversationStatus(user, statusMatch[1], { status: statusMatch[2] === "resolve" ? "RESOLVED" : "OPEN" }) }); return; }
    if (req.method === "POST" && url.pathname === "/api/v1/opportunities") { json(res, 201, { opportunity: await services.createOpportunity(user, await readBody(req)) }); return; }
    const linkMatch = url.pathname.match(/^\/api\/v1\/opportunities\/([^/]+)\/conversation$/); if (req.method === "POST" && linkMatch) { const body = await readBody(req) as { conversationId?: string }; if (!body.conversationId) throw new DomainError(422, "conversationId obrigatório"); json(res, 201, { link: await services.linkOpportunityConversation(user, linkMatch[1], body.conversationId) }); return; }
    const moveMatch = url.pathname.match(/^\/api\/v1\/opportunities\/([^/]+)\/move$/); if (req.method === "PATCH" && moveMatch) { json(res, 200, { opportunity: await services.moveOpportunity(user, moveMatch[1], await readBody(req)) }); return; }
    json(res, 404, { error: "Rota não encontrada" });
  } catch (error) { if (error instanceof DomainError) { json(res, error.status, { error: error.message }); return; } if (error instanceof Error && error.name === "ZodError") { json(res, 422, { error: "Dados inválidos" }); return; } console.error(`[api] ${req.method ?? "?"} ${req.url ?? "?"}:`, error instanceof Error ? error.message : "erro desconhecido"); json(res, 500, { error: "Erro interno" }); }
};

const server = createServer((req, res) => { void route(req, res); }); server.listen(port, () => console.log(`eChat API listening on http://localhost:${port} using PostgreSQL`)); const shutdown = () => { server.close(() => { void client.end(); }); }; process.once("SIGINT", shutdown); process.once("SIGTERM", shutdown);
